[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

board_build.sdkconfig = sdkconfig.defaults
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
board_upload.flash_size = 4MB
upload_speed = 57600

; Build script to filter filesystem uploads
extra_scripts = pre:tools/prepare_filesystem.py